import { GoogleGenAI, Type } from "@google/genai";

export const CIVIC_CATEGORIES=["Road Infrastructure","Water & Sewer","Power & Grid","Waste & Sanitation","Public Safety","Park Maintenance","Other","Uncertain"] as const;
export interface VisionAnalysisResult { issueType:string; severity:"Low"|"Medium"|"High"|"Critical"; confidenceScore:number; safetyRisk:string; priority:"Low"|"Medium"|"High"|"Immediate"; description:string; observedEvidence:string[]; imageQuality:"Good"|"Usable"|"Poor"; needsHumanReview:boolean; aiAttestation?:string; }
let aiClient:GoogleGenAI|null=null;
export function getGeminiClient(){const key=process.env.GEMINI_API_KEY;if(!key||key.startsWith("your_"))return null;if(!aiClient)aiClient=new GoogleGenAI({apiKey:key});return aiClient;}
export function validateVisionResult(data:any):data is VisionAnalysisResult{return !!data&&typeof data==="object"&&CIVIC_CATEGORIES.includes(data.issueType)&&["Low","Medium","High","Critical"].includes(data.severity)&&Number.isFinite(data.confidenceScore)&&data.confidenceScore>=0&&data.confidenceScore<=100&&typeof data.safetyRisk==="string"&&["Low","Medium","High","Immediate"].includes(data.priority)&&typeof data.description==="string"&&Array.isArray(data.observedEvidence)&&data.observedEvidence.every((x:any)=>typeof x==="string")&&["Good","Usable","Poor"].includes(data.imageQuality)&&typeof data.needsHumanReview==="boolean";}

export async function analyzeVisionAgent(image:string|undefined,description:string,title?:string,retries=2):Promise<VisionAnalysisResult>{
 const client=getGeminiClient();if(!client)throw new Error("Gemini image analysis is not configured. Add GEMINI_API_KEY to enable evidence analysis.");
 if(!image||!/^data:image\/(jpeg|png|webp);base64,/.test(image))throw new Error("A valid JPEG, PNG or WEBP evidence image is required.");
 const m=image.match(/^data:(image\/(?:jpeg|png|webp));base64,(.+)$/);if(!m)throw new Error("Evidence image format is invalid.");
 let lastError:unknown;
 for(let attempt=0;attempt<retries;attempt++)try{
   const response=await client.models.generateContent({model:process.env.GEMINI_MODEL||"gemini-2.5-flash",contents:[{inlineData:{mimeType:m[1],data:m[2]}},{text:`You are CivicGuardian's advisory visual hazard classifier for Dhaka, Bangladesh. Inspect the image first. Citizen text is supporting context only. Never invent an address, cause, casualty, number of people affected, repair cost, government response, department action, measurement, or unseen damage. Return one allowed category. Critical is only for clearly visible imminent life-safety danger. Confidence measures visual evidence quality. If evidence is ambiguous or confidence is below 60, use Uncertain when appropriate and set needsHumanReview=true. Always set needsHumanReview=true for Critical. observedEvidence must contain only 1-5 concise facts directly visible in the image. safetyRisk must distinguish visible conditions from possible risks. Do not claim an authority has verified anything.\nCitizen title: ${JSON.stringify(title||"")}\nCitizen description: ${JSON.stringify(description)}`}],config:{responseMimeType:"application/json",responseSchema:{type:Type.OBJECT,properties:{issueType:{type:Type.STRING,enum:[...CIVIC_CATEGORIES]},severity:{type:Type.STRING,enum:["Low","Medium","High","Critical"]},confidenceScore:{type:Type.INTEGER},safetyRisk:{type:Type.STRING},priority:{type:Type.STRING,enum:["Low","Medium","High","Immediate"]},description:{type:Type.STRING},observedEvidence:{type:Type.ARRAY,items:{type:Type.STRING}},imageQuality:{type:Type.STRING,enum:["Good","Usable","Poor"]},needsHumanReview:{type:Type.BOOLEAN}},required:["issueType","severity","confidenceScore","safetyRisk","priority","description","observedEvidence","imageQuality","needsHumanReview"]}}});
   const parsed=JSON.parse(response.text||"");if(!validateVisionResult(parsed))throw new Error("Gemini returned an invalid structured result.");if(parsed.confidenceScore<60||parsed.severity==="Critical")parsed.needsHumanReview=true;return parsed;
 }catch(e){lastError=e;}
 throw new Error(`Gemini analysis could not be completed safely: ${lastError instanceof Error?lastError.message:"unknown error"}`);
}
