import React,{useEffect,useMemo,useState} from "react";
import {Bell,CheckCircle2,Clock3,MapPin,PlusCircle,RefreshCw,ShieldCheck} from "lucide-react";
import type {AppUser,CivicIssue,CivicNotification} from "../types";

const statusLabel=(s:string)=>s.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const stages=["reported","under_review","verified","assigned","in_progress","resolved"];

export default function CitizenDashboard({user,onOpenReport,onReport}:{user:AppUser;onOpenReport:(i:CivicIssue)=>void;onReport:()=>void}){
 const [issues,setIssues]=useState<CivicIssue[]>([]);const [notes,setNotes]=useState<CivicNotification[]>([]);const [busy,setBusy]=useState(true);const [error,setError]=useState("");
 const load=async()=>{setBusy(true);setError("");try{const [a,b]=await Promise.all([fetch("/api/me/issues"),fetch("/api/me/notifications")]);if(!a.ok||!b.ok)throw new Error();setIssues(await a.json());setNotes(await b.json());}catch{setError("Your dashboard could not be loaded. Please try again.");}finally{setBusy(false);}};
 useEffect(()=>{void load();},[]);
 const open=issues.filter(i=>i.status!=="resolved"&&i.status!=="rejected"&&i.status!=="duplicate").length;const resolved=issues.filter(i=>i.status==="resolved").length;const unread=notes.filter(n=>!n.read).length;
 const recent=useMemo(()=>notes.slice(0,8),[notes]);
 const markRead=async(n:CivicNotification)=>{if(n.read)return;const r=await fetch(`/api/me/notifications/${n.id}/read`,{method:"POST"});if(r.ok)setNotes(x=>x.map(v=>v.id===n.id?{...v,read:true}:v));};
 return <main className="cg-dark-page min-h-[calc(100vh-72px)]"><div className="mx-auto max-w-7xl px-4 py-6 sm:px-5 lg:py-8">
  <section className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="cg-eyebrow">Citizen dashboard</div><h1 className="mt-1.5 text-2xl font-black tracking-tight text-white sm:text-3xl">Welcome back, {user.name.split(" ")[0]}</h1><p className="mt-1.5 max-w-2xl text-[13px] leading-5 text-slate-400">Track submitted hazards, status changes, and useful notifications in one place.</p></div><div className="flex gap-2"><button onClick={()=>void load()} className="cg-dark-button"><RefreshCw className={`h-4 w-4 ${busy?"animate-spin":""}`}/>Refresh</button><button onClick={onReport} className="cg-primary-button"><PlusCircle className="h-4 w-4"/>Report hazard</button></div></section>
  {error&&<div className="mt-6 rounded-xl border border-red-900/70 bg-red-950/40 p-4 text-sm text-red-200">{error}</div>}
  <section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["My reports",issues.length,MapPin,"All submissions"],["Open",open,Clock3,"Awaiting resolution"],["Resolved",resolved,CheckCircle2,"Completed reports"],["Notifications",unread,Bell,"Unread updates"]].map(([a,b,I,c]:any)=><div key={a} className="cg-dark-card"><div className="flex items-center justify-between"><span className="grid h-11 w-11 place-items-center rounded-xl bg-sky-500/10 text-sky-300"><I className="h-5 w-5"/></span><span className="text-3xl font-bold text-white">{b}</span></div><div className="mt-4 text-[16px] font-semibold text-slate-100">{a}</div><div className="mt-1 text-[13px] text-slate-400">{c}</div></div>)}</section>
  <div className="mt-7 grid gap-6 lg:grid-cols-[1.45fr_.75fr]"><section className="cg-dark-card !p-0 overflow-hidden"><div className="flex items-center justify-between border-b border-slate-800 px-5 py-4"><div><h2 className="font-black text-white">My reports</h2><p className="mt-1 text-xs text-slate-500">Every report remains traceable by its CivicGuardian ID.</p></div><ShieldCheck className="h-5 w-5 text-sky-300"/></div>{!busy&&issues.length===0?<div className="p-10 text-center"><MapPin className="mx-auto h-8 w-8 text-slate-600"/><div className="mt-3 font-bold text-slate-200">No reports yet</div><p className="mt-1 text-sm text-slate-500">Your real submitted reports will appear here.</p></div>:<div className="divide-y divide-slate-800">{issues.map(i=>{const stage=Math.max(0,stages.indexOf(i.status));return <button key={i.id} onClick={()=>onOpenReport(i)} className="block w-full px-5 py-4 text-left transition hover:bg-slate-800/45"><div className="flex flex-wrap items-start justify-between gap-2"><div><div className="text-[10px] font-black uppercase tracking-[.14em] text-sky-300">{i.id} · {i.category}</div><div className="mt-1 font-extrabold text-slate-100">{i.title}</div><div className="mt-1 flex items-center gap-1 text-xs text-slate-500"><MapPin className="h-3 w-3"/>{i.address}</div></div><span className="rounded-full border border-slate-700 bg-slate-900 px-2.5 py-1 text-[10px] font-black text-slate-300">{statusLabel(i.status)}</span></div><div className="mt-4 flex gap-1">{stages.map((s,index)=><span key={s} title={statusLabel(s)} className={`h-1.5 flex-1 rounded-full ${index<=stage?"bg-sky-500":"bg-slate-800"}`}/>)}</div></button>})}</div>}</section>
   <aside className="cg-dark-card !p-0 overflow-hidden"><div className="flex items-center justify-between border-b border-slate-800 px-5 py-4"><div><h2 className="font-black text-white">Notifications</h2><p className="mt-1 text-xs text-slate-500">Report and review updates</p></div>{unread>0&&<span className="rounded-full bg-sky-500 px-2 py-0.5 text-[10px] font-black text-white">{unread} new</span>}</div><div className="divide-y divide-slate-800">{recent.length?recent.map(n=><button key={n.id} onClick={()=>void markRead(n)} className={`w-full p-4 text-left ${n.read?"bg-transparent":"bg-sky-500/[.04]"}`}><div className="flex gap-3"><span className={`mt-1 h-2 w-2 shrink-0 rounded-full ${n.read?"bg-slate-700":"bg-sky-400"}`}/><div><div className="text-xs font-extrabold text-slate-200">{n.title}</div><p className="mt-1 text-xs leading-5 text-slate-500">{n.message}</p><div className="mt-1 text-[10px] text-slate-600">{new Date(n.createdAt).toLocaleString()}</div></div></div></button>):<div className="p-8 text-center text-sm text-slate-500">No notifications yet.</div>}</div></aside>
  </div>
 </div></main>;
}
