import React,{useEffect,useState} from "react";
import {Award,CheckCircle2,FileWarning,HeartHandshake} from "lucide-react";
import type {ContributorSummary} from "../types";

export default function CommunityHeroes(){
 const [heroes,setHeroes]=useState<ContributorSummary[]>([]);const [busy,setBusy]=useState(true);
 useEffect(()=>{fetch("/api/contributors").then(r=>r.ok?r.json():[]).then(setHeroes).catch(()=>setHeroes([])).finally(()=>setBusy(false));},[]);
 return <main className="cg-dark-page min-h-[calc(100vh-72px)]"><div className="mx-auto max-w-7xl px-5 py-10 sm:px-6 lg:py-14">
  <div className="max-w-3xl"><div className="cg-eyebrow flex items-center gap-2"><Award className="h-4 w-4"/>Community heroes</div><h1 className="mt-3 text-3xl font-black tracking-tight text-white sm:text-5xl">Recognition earned through real civic action.</h1><p className="mt-4 text-sm leading-7 text-slate-400">CivicGuardian ranks contributors only from recorded reports, community verification actions and helpful votes. Empty data stays empty. No names, points or achievements are invented.</p></div>
  <div className="mt-8 grid gap-4 md:grid-cols-3">{[[FileWarning,"Report responsibly","5 points per submitted report"],[CheckCircle2,"Verify locally","2 points per verification"],[HeartHandshake,"Help the community","1 point per helpful vote"]].map(([I,t,d]:any)=><div key={t} className="cg-dark-card"><I className="h-5 w-5 text-sky-300"/><h2 className="mt-4 font-extrabold text-white">{t}</h2><p className="mt-1 text-xs text-slate-500">{d}</p></div>)}</div>
  <section className="mt-8 overflow-hidden rounded-2xl border border-[#223148] bg-[#101925]"><div className="flex items-end justify-between gap-4 border-b border-[#223148] px-5 py-5 sm:px-7"><div><div className="text-xs font-extrabold uppercase tracking-[.15em] text-sky-300">Leaderboard</div><h2 className="mt-1 text-xl font-black text-white">Top contributors</h2></div><span className="hidden text-[10px] font-bold uppercase tracking-wider text-slate-500 sm:block">Reports ×5 · checks ×2 · votes ×1</span></div>
   {busy?<div className="p-10 text-center text-sm text-slate-500">Loading community activity…</div>:heroes.length?<div className="divide-y divide-[#223148]">{heroes.map((h,index)=><div key={h.id} className="grid gap-4 px-5 py-5 sm:grid-cols-[70px_1fr_auto] sm:items-center sm:px-7"><span className="grid h-11 w-11 place-items-center rounded-xl bg-sky-500/10 text-sm font-black text-sky-300">#{index+1}</span><div className="min-w-0"><div className="truncate font-extrabold text-slate-100">{h.name}</div><div className="mt-1 text-xs text-slate-500">{h.reports} reports · {h.verifications} checks · {h.helpfulVotes} helpful votes</div></div><div className="text-left sm:text-right"><b className="text-2xl text-white">{h.score}</b><div className="text-[10px] font-bold uppercase tracking-wider text-slate-500">points</div></div></div>)}</div>:<div className="p-12 text-center"><Award className="mx-auto h-8 w-8 text-slate-600"/><div className="mt-3 font-bold text-slate-300">No contributor ranking yet</div><p className="mt-1 text-sm text-slate-500">The leaderboard will populate only after real CivicGuardian activity.</p></div>}
  </section>
 </div></main>;
}
