import React,{useEffect,useState} from "react";
import {Award,CheckCircle2,FileWarning,HeartHandshake} from "lucide-react";
import type {ContributorSummary} from "../types";

export default function CommunityHeroes(){
 const [heroes,setHeroes]=useState<ContributorSummary[]>([]);const [busy,setBusy]=useState(true);
 useEffect(()=>{fetch("/api/contributors").then(r=>r.ok?r.json():[]).then(setHeroes).catch(()=>setHeroes([])).finally(()=>setBusy(false));},[]);
 return <main className="cg-dark-page min-h-[calc(100vh-72px)]"><div className="mx-auto max-w-7xl px-4 py-6 sm:px-5 lg:py-8">
  <div className="max-w-2xl"><div className="cg-eyebrow flex items-center gap-2"><Award className="h-3.5 w-3.5"/>Community heroes</div><h1 className="mt-2 text-2xl font-black tracking-tight text-white sm:text-3xl">Recognition for verified civic action</h1><p className="mt-2 text-[13px] leading-6 text-slate-400">Points come only from recorded reports, local verification, and helpful votes. No names or achievements are invented.</p></div>
  <div className="mt-6 grid gap-4 md:grid-cols-3">{[[FileWarning,"Report responsibly","5 points per submitted report"],[CheckCircle2,"Verify locally","2 points per verification"],[HeartHandshake,"Help the community","1 point per helpful vote"]].map(([I,t,d]:any)=><div key={t} className="cg-dark-card flex items-center gap-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-sky-500/10"><I className="h-5 w-5 text-sky-300"/></span><div><h2 className="text-[17px] font-semibold text-white">{t}</h2><p className="mt-1 text-[14px] text-slate-400">{d}</p></div></div>)}</div>
  <section className="mt-6 overflow-hidden rounded-2xl border border-[#223148] bg-[#101925]"><div className="flex items-end justify-between gap-4 border-b border-[#223148] px-5 py-5 sm:px-6"><div><div className="text-[13px] font-semibold uppercase tracking-[.12em] text-sky-300">Leaderboard</div><h2 className="mt-1 text-2xl font-bold text-white">Top contributors</h2></div><span className="hidden text-[12px] font-semibold uppercase tracking-wider text-slate-400 sm:block">Reports ×5 · checks ×2 · votes ×1</span></div>
   {busy?<div className="space-y-2 p-4">{[1,2,3].map(i=><div key={i} className="cg-skeleton h-16 rounded-lg bg-slate-800"/>)}</div>:heroes.length?<div className="divide-y divide-[#223148]">{heroes.map((h,index)=><div key={h.id} className="grid gap-3 px-4 py-3.5 sm:grid-cols-[54px_1fr_auto] sm:items-center sm:px-5"><span className="grid h-9 w-9 place-items-center rounded-lg bg-sky-500/10 text-xs font-black text-sky-300">#{index+1}</span><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><div className="truncate text-[13px] font-extrabold text-slate-100">{h.name}</div>{h.role==="admin"&&<span className="rounded bg-violet-500/15 px-2 py-0.5 text-[8px] font-black uppercase text-violet-300">Admin</span>}</div><div className="mt-0.5 text-[11px] text-slate-500">{h.reports} reports · {h.verifications} checks · {h.helpfulVotes} helpful votes</div>{h.badges?.length?<div className="mt-1.5 flex flex-wrap gap-1">{h.badges.map(badge=><span key={badge} className="rounded-full border border-slate-700 px-2 py-0.5 text-[8px] font-bold text-sky-300">{badge}</span>)}</div>:null}</div><div className="text-left sm:text-right"><b className="text-xl text-white">{h.score}</b><div className="text-[9px] font-bold uppercase tracking-wider text-slate-500">points</div></div></div>)}</div>:<div className="p-8 text-center"><Award className="mx-auto h-7 w-7 text-slate-600"/><div className="mt-2 text-[13px] font-bold text-slate-300">No contributor ranking yet</div><p className="mt-1 text-xs text-slate-500">The leaderboard will populate only after real CivicGuardian activity.</p></div>}
  </section>
 </div></main>;
}
