import React,{useEffect,useMemo,useState} from "react";
import { Award,CheckCircle2,MapPin,Search,ShieldAlert,ThumbsUp,Users } from "lucide-react";
import type { CivicIssue,ContributorSummary,DashboardMetrics } from "../types";
import MapView from "./dashboard/MapView";
import { IssueImage } from "./common/IssueImage";
export default function CommunityDashboard({issues,metrics,onUpvote,onVerify,onNotAccurate,onSelectIssue,setActiveTab}:{issues:CivicIssue[];metrics:DashboardMetrics;onUpvote:(id:string)=>Promise<void>;onVerify:(id:string)=>Promise<void>;onNotAccurate:(id:string)=>Promise<void>;onSelectIssue:(i:CivicIssue)=>void;setActiveTab:(s:string)=>void}){
 const [q,setQ]=useState("");const [filter,setFilter]=useState("All");const [heroes,setHeroes]=useState<ContributorSummary[]>([]);const filtered=useMemo(()=>issues.filter(i=>(filter==="All"||i.status===filter)&&`${i.title} ${i.address} ${i.category}`.toLowerCase().includes(q.toLowerCase())),[issues,q,filter]);
 useEffect(()=>{fetch("/api/contributors").then(r=>r.ok?r.json():[]).then(setHeroes).catch(()=>setHeroes([]));},[issues]);
 const openIssue=(i:CivicIssue)=>{onSelectIssue(i);setActiveTab("detail")};
 return <main className="mx-auto max-w-7xl space-y-9 px-6 py-10"><section className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><div className="text-xs font-black uppercase tracking-[.18em] text-teal-700">Dhaka community safety</div><h1 className="mt-2 text-3xl font-black tracking-tight text-slate-950">Hazard map & public reports</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Public reports show citizen-submitted evidence and AI-assisted assessment. Official status changes are controlled by authorized administrators.</p></div><button onClick={()=>setActiveTab("report")} className="rounded-xl bg-teal-700 px-5 py-3 text-sm font-bold text-white hover:bg-teal-800">+ Report a hazard</button></section>
 <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Total reports",metrics.totalIssues,Users],["Critical",metrics.criticalCount,ShieldAlert],["Resolved",metrics.resolvedIssues,CheckCircle2],["Verified actions",metrics.totalVerifiedCount||0,ThumbsUp]].map(([l,v,I]:any)=><div key={l} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><I className="h-5 w-5 text-teal-700"/><div className="mt-4 text-2xl font-black text-slate-950">{v}</div><div className="mt-1 text-xs font-bold uppercase tracking-wider text-slate-400">{l}</div></div>)}</section>
 <MapView issues={issues} onSelectIssue={openIssue}/>
 <section className="overflow-hidden rounded-2xl border border-[#223149] bg-[#0b1220] p-6 text-white shadow-xl sm:p-7"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="flex items-center gap-2 text-[11px] font-black uppercase tracking-[.17em] text-sky-300"><Award className="h-4 w-4"/>Community heroes</div><h2 className="mt-2 text-2xl font-black">Top contributors</h2><p className="mt-1 text-xs leading-5 text-slate-400">Ranking is calculated only from real CivicGuardian activity: submitted reports, community verifications and helpful votes.</p></div><button onClick={()=>setActiveTab("heroes")} className="text-xs font-extrabold text-sky-300 transition hover:text-sky-200">View full leaderboard →</button></div>{heroes.length?<div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{heroes.slice(0,8).map((h,index)=><div key={h.id} className="rounded-xl border border-slate-800 bg-[#111b2b] p-4"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-full bg-sky-400/10 text-xs font-black text-sky-300">#{index+1}</span><div className="min-w-0"><div className="truncate text-sm font-extrabold text-slate-100">{h.name}</div><div className="text-[10px] font-bold text-slate-500">{h.score} contribution points</div></div></div><div className="mt-4 grid grid-cols-3 gap-1 text-center"><div><b className="block text-sm text-white">{h.reports}</b><span className="text-[9px] uppercase text-slate-600">reports</span></div><div><b className="block text-sm text-white">{h.verifications}</b><span className="text-[9px] uppercase text-slate-600">checks</span></div><div><b className="block text-sm text-white">{h.helpfulVotes}</b><span className="text-[9px] uppercase text-slate-600">votes</span></div></div></div>)}</div>:<div className="mt-6 rounded-xl border border-dashed border-slate-700 p-8 text-center text-sm text-slate-500">No contributor ranking yet. CivicGuardian will not invent leaderboard entries.</div>}</section>
 <section><div className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-3 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search reports or locations" className="w-full rounded-xl border border-slate-200 py-2.5 pl-9 pr-3 text-sm outline-none focus:border-teal-600"/></div><select value={filter} onChange={e=>setFilter(e.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm">{[["All","All status"],["reported","Reported"],["under_review","Under review"],["in_progress","In progress"],["resolved","Resolved"]].map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></div><div className="mt-5 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{filtered.map(i=>{const sev=i.analysis?.vision?.severity||"Unassessed";return <article key={i.id} className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><button onClick={()=>openIssue(i)} className="block w-full text-left"><IssueImage src={i.imageUrl} alt={i.title} className="h-44 w-full object-cover"/><div className="p-5"><div className="flex items-center justify-between gap-2"><span className="text-[10px] font-black uppercase tracking-wider text-teal-700">{i.category}</span><span className="rounded-full bg-slate-100 px-2 py-1 text-[9px] font-bold uppercase text-slate-500">{i.status.replace("_"," ")}</span></div><h3 className="mt-2 line-clamp-2 font-black text-slate-900">{i.title}</h3><p className="mt-2 flex items-start gap-1 text-xs text-slate-500"><MapPin className="mt-.5 h-3.5 w-3.5 shrink-0"/>{i.address}</p><div className="mt-3 text-xs font-bold text-slate-500">AI severity: <span className="text-slate-800">{sev}</span></div></div></button><div className="grid grid-cols-3 border-t border-slate-100 text-[11px] font-bold"><button onClick={()=>onUpvote(i.id)} className={`p-3 hover:bg-slate-50 ${i.isUpvotedByMe?"text-teal-700":"text-slate-500"}`}>↑ {i.upvotes}</button><button onClick={()=>onVerify(i.id)} className={`border-x border-slate-100 p-3 hover:bg-slate-50 ${i.isVerifiedByMe?"text-teal-700":"text-slate-500"}`}>✓ {i.verifiedByCount}</button><button onClick={()=>onNotAccurate(i.id)} className={`p-3 hover:bg-slate-50 ${i.isNotAccurateByMe?"text-red-600":"text-slate-500"}`}>Dispute</button></div></article>})}</div></section>
 </main>;
}
