import React,{useMemo,useState} from "react";
import { MapContainer,Marker,Popup,TileLayer,useMap } from "react-leaflet";
import L from "leaflet";
import { Crosshair,MapPin,Search,ShieldCheck } from "lucide-react";
import type { CivicIssue } from "../../types";
import "leaflet/dist/leaflet.css";

const DHAKA_BOUNDS:L.LatLngBoundsExpression=[[23.60,90.25],[24.02,90.55]];
const colors:Record<string,string>={Critical:"#dc2626",High:"#ea580c",Medium:"#d97706",Low:"#0f766e",Unassessed:"#64748b"};
const marker=(severity:string)=>L.divIcon({className:"",html:`<span style="display:block;width:20px;height:20px;border:3px solid white;border-radius:999px;background:${colors[severity]||colors.Medium};box-shadow:0 2px 9px #0f172a55"></span>`,iconSize:[20,20],iconAnchor:[10,10]});
const searchMarker=L.divIcon({className:"",html:'<span style="display:block;width:25px;height:25px;border:5px solid white;border-radius:999px;background:#0284c7;box-shadow:0 3px 14px #0f172a66"></span>',iconSize:[25,25],iconAnchor:[12,12]});
function Locate(){const map=useMap();return <button onClick={()=>navigator.geolocation?.getCurrentPosition(p=>map.flyTo([p.coords.latitude,p.coords.longitude],15))} className="absolute right-3 top-3 z-[500] flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-bold text-slate-700 shadow"><Crosshair className="h-4 w-4 text-teal-700"/>My location</button>}
function FlyToSearch({point}:{point:[number,number]|null}){const map=useMap();React.useEffect(()=>{if(point)map.flyTo(point,15,{duration:.55});},[map,point]);return null;}
export default function MapView({issues,onSelectIssue}:{issues:CivicIssue[];onSelectIssue:(i:CivicIssue)=>void}){
 const [category,setCategory]=useState("All");const [severity,setSeverity]=useState("All");const [query,setQuery]=useState("");const [searchPoint,setSearchPoint]=useState<[number,number]|null>(null);const [placeName,setPlaceName]=useState("");const [searching,setSearching]=useState(false);const [searchError,setSearchError]=useState("");
 const filtered=useMemo(()=>issues.filter(i=>(category==="All"||i.category===category)&&(severity==="All"||(i.analysis?.vision?.severity||"Medium")===severity)),[issues,category,severity]);
 const searchPlace=async(e:React.FormEvent)=>{e.preventDefault();if(query.trim().length<2)return;setSearching(true);setSearchError("");try{const r=await fetch(`/api/geocode/search?q=${encodeURIComponent(query.trim())}`);const d=await r.json();if(!r.ok)throw new Error(d.error);const hit=d.results?.[0];if(!hit){setSearchError("No matching Dhaka location found.");setSearchPoint(null);setPlaceName("");return;}setSearchPoint([Number(hit.lat),Number(hit.lon)]);setPlaceName(hit.display_name);}catch{setSearchError("Location search is temporarily unavailable.");}finally{setSearching(false);}};
 const categories=["All",...Array.from(new Set(issues.map(i=>i.category)))];
 return <div className="grid min-w-0 gap-5 lg:grid-cols-[300px_minmax(0,1fr)]"><aside className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2 text-xs font-extrabold uppercase tracking-[.16em] text-sky-700"><ShieldCheck className="h-4 w-4"/>Dhaka coverage</div><h3 className="mt-3 text-xl font-black text-slate-900">Live hazard map</h3><p className="mt-1 text-xs leading-5 text-slate-500">Search a real Dhaka place or filter citizen reports. Search immediately marks the best matching place.</p><form onSubmit={searchPlace} className="mt-5 space-y-2"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="e.g. Mirpur 10" className="w-full rounded-xl border border-slate-200 py-2.5 pl-9 pr-3 text-sm outline-none focus:border-sky-600"/></div><button disabled={searching||query.trim().length<2} className="w-full rounded-xl bg-sky-700 px-3 py-2.5 text-xs font-black text-white hover:bg-sky-600 disabled:opacity-40">{searching?"Searching...":"Find on map"}</button></form>{placeName&&<div className="mt-3 rounded-xl border border-sky-200 bg-sky-50 p-3 text-xs leading-5 text-sky-950"><strong>Marked:</strong> {placeName}</div>}{searchError&&<div className="mt-3 text-xs text-red-600">{searchError}</div>}<label className="mt-4 block text-[10px] font-bold uppercase tracking-wider text-slate-400">Category</label><select value={category} onChange={e=>setCategory(e.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm">{categories.map(c=><option key={c}>{c}</option>)}</select><label className="mt-4 block text-[10px] font-bold uppercase tracking-wider text-slate-400">Severity</label><select value={severity} onChange={e=>setSeverity(e.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm">{["All","Critical","High","Medium","Low"].map(s=><option key={s}>{s}</option>)}</select><div className="mt-5 rounded-xl bg-sky-50 p-3 text-xs text-sky-900"><strong>{filtered.length}</strong> visible reports in the current filters.</div></aside>
 <div className="relative z-0 h-[540px] min-w-0 max-w-full overflow-hidden rounded-2xl border border-slate-200 bg-slate-100 shadow-sm"><MapContainer bounds={DHAKA_BOUNDS} maxBounds={DHAKA_BOUNDS} minZoom={10} style={{height:"100%",width:"100%",position:"relative",zIndex:0}} scrollWheelZoom><TileLayer attribution='&copy; OpenStreetMap contributors &copy; CARTO' url="https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png"/><Locate/><FlyToSearch point={searchPoint}/>{searchPoint&&<Marker position={searchPoint} icon={searchMarker}><Popup><strong>{placeName||"Search result"}</strong></Popup></Marker>}{filtered.filter(i=>i.lat&&i.lng).map(i=>{const s=i.analysis?.vision?.severity||"Unassessed";return <Marker key={i.id} position={[i.lat!,i.lng!]} icon={marker(s)}><Popup><div className="min-w-52"><div className="text-[10px] font-bold uppercase tracking-wider" style={{color:colors[s]}}>{s} · {i.category}</div><strong className="mt-1 block text-sm">{i.title}</strong><div className="mt-1 flex gap-1 text-xs text-slate-500"><MapPin className="h-3 w-3 shrink-0"/>{i.address}</div><button onClick={()=>onSelectIssue(i)} className="mt-3 rounded-lg bg-teal-700 px-3 py-1.5 text-xs font-bold text-white">Open report</button></div></Popup></Marker>})}</MapContainer><div className="pointer-events-none absolute bottom-3 left-3 z-[500] max-w-[calc(100%-1.5rem)] rounded-lg bg-white/95 px-3 py-2 text-[10px] font-semibold text-slate-500 shadow">Dhaka service view · English place search · Map data © OpenStreetMap contributors, CARTO</div></div></div>;
}
